apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 932267165833.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 932267165833.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: c993d0e9
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
